<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Business\EvilCase.Domain\EvilCase.Domain.csproj" />
    <ProjectReference Include="..\..\Utils\EvilBrains.EntityFramework\EvilBrains.EntityFramework.csproj" />
  </ItemGroup>

</Project>
