<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EvilBrains.Logging.Contract\EvilBrains.Logging.Contract.csproj" />
  </ItemGroup>

</Project>
