using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EvilBrains.ApiClient.Generator;

/// <summary>
/// Emits generated sources with fixed "\n" line endings so the output does not depend on the host platform.
/// The HTTP mechanics live in EvilBrains.ApiClient.ApiClientHttp; each action becomes a single executor call.
/// </summary>
internal static class ClientEmitter
{
    private const string Header = "// <auto-generated/>\n#nullable enable\n\n";

    private const string GeneratedCode = "[global::System.CodeDom.Compiler.GeneratedCode(\"EvilBrains.ApiClient.Generator\", \"1.0.0\")]\n";

    private const string Helpers = "global::EvilBrains.ApiClient.ApiClientHttp";

    private const string TaskType = "global::System.Threading.Tasks.Task";

    private const string ServicesType = "global::Microsoft.Extensions.DependencyInjection.IServiceCollection";

    private const string BuilderType = "global::Microsoft.Extensions.DependencyInjection.IHttpClientBuilder";

    public static string EmitClient(string ns, ClientModel client)
    {
        var source = new StringBuilder();
        source.Append(Header);
        source.Append("namespace ").Append(ns).Append(";\n\n");
        source.Append("/// <summary>Generated HTTP client for the ").Append(client.Name).Append(" API.</summary>\n");
        source.Append(GeneratedCode);
        source.Append("public interface I").Append(client.Name).Append("Client\n{\n");

        foreach (var action in client.Actions)
        {
            source.Append("    /// <summary>Calls ").Append(action.HttpMethod.ToUpperInvariant()).Append(' ').Append(action.Route).Append(".</summary>\n");
            source.Append("    ").Append(ReturnType(action)).Append(' ').Append(action.Name).Append('(').Append(Parameters(action)).Append(");\n");
        }

        source.Append("}\n\n");
        source.Append(GeneratedCode);
        source.Append("internal sealed class ").Append(client.Name).Append("Client : I").Append(client.Name).Append("Client\n{\n");
        source.Append("    private readonly global::System.Net.Http.HttpClient httpClient;\n\n");
        source.Append("    public ").Append(client.Name).Append("Client(global::System.Net.Http.HttpClient httpClient)\n");
        source.Append("    {\n        this.httpClient = httpClient;\n    }\n");

        foreach (var action in client.Actions)
        {
            source.Append('\n');
            EmitMethod(source, action);
        }

        source.Append("}\n");

        return source.ToString();
    }

    public static string EmitRegistrations(string ns, ApiModel model)
    {
        var source = new StringBuilder();
        source.Append(Header);
        source.Append("namespace ").Append(ns).Append(";\n\n");
        source.Append(GeneratedCode);
        source.Append("internal static class ApiClientRegistrations\n{\n");
        source.Append("    public static ").Append(ServicesType).Append(" AddGeneratedApiClients(\n");
        source.Append("        this ").Append(ServicesType).Append(" services,\n");
        source.Append("        global::System.Action<global::System.Net.Http.HttpClient> configure,\n");
        source.Append("        global::System.Action<").Append(BuilderType).Append(">? configureClient = null)\n    {\n");

        var declared = false;
        foreach (var client in model.Clients)
        {
            source.Append("        ").Append(declared ? "" : BuilderType + " ").Append("builder = ");
            source.Append("global::Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions.AddHttpClient<");
            source.Append("global::").Append(ns).Append(".I").Append(client.Name).Append("Client, ");
            source.Append("global::").Append(ns).Append('.').Append(client.Name).Append("Client>(services, configure);\n");

            // Not configureClient?.Invoke(AddHttpClient(...)): the null-conditional would skip the registration.
            source.Append("        configureClient?.Invoke(builder);\n");
            declared = true;
        }

        source.Append("\n        return services;\n    }\n}\n");

        return source.ToString();
    }

    private static void EmitMethod(StringBuilder source, ActionModel action)
    {
        source.Append("    public ").Append(ReturnType(action)).Append(' ').Append(action.Name).Append('(').Append(Parameters(action)).Append(") =>\n");
        source.Append("        ").Append(Helpers).Append('.').Append(Executor(action)).Append('(');
        source.Append("this.httpClient, global::System.Net.Http.HttpMethod.").Append(action.HttpMethod).Append(", ").Append(UrlExpression(action)).Append(", ").Append(TokenExpression(action));

        var body = action.Parameters.FirstOrDefault(static x => x.Kind == ParameterKind.Body);
        if (body is not null)
            source.Append(", body: ").Append(body.Name);

        var query = QueryPairs(action);
        if (query.Count > 0)
            source.Append(", query: [").Append(string.Join(", ", query)).Append(']');

        var headers = HeaderPairs(action);
        if (headers.Count > 0)
            source.Append(", headers: [").Append(string.Join(", ", headers)).Append(']');

        source.Append(");\n");
    }

    private static string Executor(ActionModel action)
    {
        if (action.ResultType is null)
            return "Send";

        var name = action.ResultIsNullable ? "SendNullable" : "Send";

        return name + "<" + action.ResultType + ">";
    }

    private static string TokenExpression(ActionModel action)
    {
        var token = action.Parameters.FirstOrDefault(static x => x.Kind == ParameterKind.Token);

        return token is null ? "global::System.Threading.CancellationToken.None" : token.Name;
    }

    private static List<string> QueryPairs(ActionModel action)
    {
        var pairs = new List<string>();

        foreach (var parameter in action.Parameters)
        {
            if (parameter.Kind == ParameterKind.Query)
            {
                pairs.Add($"(\"{parameter.WireName}\", {parameter.Name})");

                continue;
            }

            if (parameter.Kind != ParameterKind.QueryObject)
                continue;

            var access = parameter.IsNullable ? parameter.Name + "?." : parameter.Name + ".";
            foreach (var property in parameter.QueryProperties)
                pairs.Add($"(\"{property.WireName}\", {access}{property.PropertyName})");
        }

        return pairs;
    }

    private static List<string> HeaderPairs(ActionModel action)
    {
        var pairs = new List<string>();

        foreach (var parameter in action.Parameters.Where(static x => x.Kind == ParameterKind.Header))
            pairs.Add($"(\"{parameter.WireName}\", {parameter.Name})");

        return pairs;
    }

    private static string UrlExpression(ActionModel action)
    {
        var result = new StringBuilder();
        var interpolated = false;
        var route = action.Route;
        var i = 0;

        while (i < route.Length)
        {
            if (route[i] != '{')
            {
                result.Append(route[i]);
                i++;

                continue;
            }

            var start = i + 1;
            var end = start;
            while (end < route.Length && (char.IsLetterOrDigit(route[end]) || route[end] == '_'))
                end++;

            var placeholder = route.Substring(start, end - start);
            var parameter = action.Parameters.First(x => x.Kind == ParameterKind.Route && string.Equals(x.WireName, placeholder, StringComparison.OrdinalIgnoreCase));

            result.Append("{(").Append(Helpers).Append(".Route(").Append(parameter.Name).Append("))}");
            interpolated = true;

            var close = route.IndexOf('}', end);
            i = close < 0 ? route.Length : close + 1;
        }

        var prefix = interpolated ? "$\"" : "\"";

        return prefix + result + "\"";
    }

    private static string ReturnType(ActionModel action)
    {
        return action.ResultType is null ? TaskType : $"{TaskType}<{action.ResultType}>";
    }

    private static string Parameters(ActionModel action)
    {
        var parameters = action.Parameters
            .Where(static x => x.Kind != ParameterKind.Skipped)
            .Select(static x => x.DefaultValue is null ? $"{x.Type} {x.Name}" : $"{x.Type} {x.Name} = {x.DefaultValue}");

        return string.Join(", ", parameters);
    }
}
