using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EvilBrains.ApiClient.Generator;

/// <summary>
/// Emits generated sources with fixed "\n" line endings so the output does not depend on the host platform.
/// </summary>
internal static class ClientEmitter
{
    private const string Header = "// <auto-generated/>\n#nullable enable\n\n";

    private const string GeneratedCode = "[global::System.CodeDom.Compiler.GeneratedCode(\"EvilBrains.ApiClient.Generator\", \"1.0.0\")]\n";

    private const string Helpers = "global::EvilBrains.ApiClient.ApiClientHttp";

    private const string TaskType = "global::System.Threading.Tasks.Task";

    private const string ServicesType = "global::Microsoft.Extensions.DependencyInjection.IServiceCollection";

    public static string EmitClient(string ns, ClientModel client)
    {
        var source = new StringBuilder();
        source.Append(Header);
        source.Append("namespace ").Append(ns).Append(";\n\n");
        source.Append("/// <summary>Generated HTTP client for the ").Append(client.Name).Append(" API.</summary>\n");
        source.Append(GeneratedCode);
        source.Append("public interface I").Append(client.Name).Append("Client\n{\n");

        foreach (var action in client.Actions)
        {
            source.Append("    /// <summary>Calls ").Append(action.HttpMethod.ToUpperInvariant()).Append(' ').Append(action.Route).Append(".</summary>\n");
            source.Append("    ").Append(ReturnType(action)).Append(' ').Append(action.Name).Append('(').Append(Parameters(action)).Append(");\n");
        }

        source.Append("}\n\n");
        source.Append(GeneratedCode);
        source.Append("internal sealed class ").Append(client.Name).Append("Client : I").Append(client.Name).Append("Client\n{\n");
        source.Append("    private readonly global::System.Net.Http.HttpClient httpClient;\n\n");
        source.Append("    public ").Append(client.Name).Append("Client(global::System.Net.Http.HttpClient httpClient)\n");
        source.Append("    {\n        this.httpClient = httpClient;\n    }\n");

        foreach (var action in client.Actions)
        {
            source.Append('\n');
            EmitMethod(source, action);
        }

        source.Append("}\n");

        return source.ToString();
    }

    public static string EmitRegistrations(string ns, ApiModel model)
    {
        var source = new StringBuilder();
        source.Append(Header);
        source.Append("namespace ").Append(ns).Append(";\n\n");
        source.Append(GeneratedCode);
        source.Append("internal static class ApiClientRegistrations\n{\n");
        source.Append("    public static ").Append(ServicesType).Append(" AddGeneratedApiClients(\n");
        source.Append("        this ").Append(ServicesType).Append(" services,\n");
        source.Append("        global::System.Action<global::System.Net.Http.HttpClient> configure)\n    {\n");

        foreach (var client in model.Clients)
        {
            source.Append("        global::Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions.AddHttpClient<");
            source.Append("global::").Append(ns).Append(".I").Append(client.Name).Append("Client, ");
            source.Append("global::").Append(ns).Append('.').Append(client.Name).Append("Client>(services, configure);\n");
        }

        source.Append("\n        return services;\n    }\n}\n");

        return source.ToString();
    }

    private static void EmitMethod(StringBuilder source, ActionModel action)
    {
        var tokenParameter = action.Parameters.FirstOrDefault(x => x.Kind == ParameterKind.Token);
        var token = tokenParameter is null ? "global::System.Threading.CancellationToken.None" : tokenParameter.Name;

        source.Append("    public async ").Append(ReturnType(action)).Append(' ').Append(action.Name).Append('(').Append(Parameters(action)).Append(")\n    {\n");
        EmitUrl(source, action);

        source.Append("        using var __request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.").Append(action.HttpMethod).Append(", __url);\n");
        EmitHeaders(source, action);

        var body = action.Parameters.FirstOrDefault(x => x.Kind == ParameterKind.Body);
        if (body is not null)
            source.Append("        __request.Content = global::System.Net.Http.Json.JsonContent.Create(").Append(body.Name).Append(", options: ").Append(Helpers).Append(".JsonOptions);\n");

        source.Append("        using var __response = await this.httpClient.SendAsync(__request, ").Append(token).Append(").ConfigureAwait(false);\n");
        source.Append("        await ").Append(Helpers).Append(".EnsureSuccessAsync(__response, ").Append(token).Append(").ConfigureAwait(false);\n");

        if (action.ResultType is not null)
        {
            var terminator = action.ResultIsNullable ? ";\n" : "\n            ?? throw new global::EvilBrains.ApiClient.ApiException(__response.StatusCode, null);\n";
            source.Append("        return await global::System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync<").Append(action.ResultType).Append(">(");
            source.Append("__response.Content, ").Append(Helpers).Append(".JsonOptions, ").Append(token).Append(").ConfigureAwait(false)").Append(terminator);
        }

        source.Append("    }\n");
    }

    private static void EmitHeaders(StringBuilder source, ActionModel action)
    {
        foreach (var header in action.Parameters.Where(x => x.Kind == ParameterKind.Header))
        {
            var line = $"__request.Headers.TryAddWithoutValidation(\"{header.WireName}\", {Helpers}.Format({header.Name}));";
            if (header.IsNullable)
            {
                source.Append("        if (").Append(header.Name).Append(" is not null)\n            ").Append(line).Append('\n');

                continue;
            }

            source.Append("        ").Append(line).Append('\n');
        }
    }

    private static void EmitUrl(StringBuilder source, ActionModel action)
    {
        source.Append("        var __url = ").Append(UrlExpression(action)).Append(";\n");

        var queries = action.Parameters.Where(x => x.Kind is ParameterKind.Query or ParameterKind.QueryObject).ToList();
        if (queries.Count == 0)
            return;

        source.Append("        var __query = new global::System.Collections.Generic.List<string>();\n");

        foreach (var parameter in queries)
        {
            if (parameter.Kind == ParameterKind.Query)
            {
                EmitQueryAdd(source, parameter.WireName, parameter.Name, parameter.IsNullable ? parameter.Name + " is not null" : null);

                continue;
            }

            foreach (var property in parameter.QueryProperties)
            {
                var expression = parameter.Name + "." + property.PropertyName;
                EmitQueryAdd(source, property.WireName, expression, BuildGuard(parameter, property, expression));
            }
        }

        source.Append("        if (__query.Count > 0)\n            __url += \"?\" + string.Join(\"&\", __query);\n");
    }

    private static void EmitQueryAdd(StringBuilder source, string wireName, string valueExpression, string? guard)
    {
        var add = $"__query.Add(\"{wireName}=\" + global::System.Uri.EscapeDataString({Helpers}.Format({valueExpression})));";
        if (guard is null)
        {
            source.Append("        ").Append(add).Append('\n');

            return;
        }

        source.Append("        if (").Append(guard).Append(")\n            ").Append(add).Append('\n');
    }

    private static string? BuildGuard(ParameterModel parameter, QueryPropertyModel property, string expression)
    {
        var conditions = new List<string>();
        if (parameter.IsNullable)
            conditions.Add(parameter.Name + " is not null");

        if (property.IsNullable)
            conditions.Add(expression + " is not null");

        return conditions.Count == 0 ? null : string.Join(" && ", conditions);
    }

    private static string UrlExpression(ActionModel action)
    {
        var result = new StringBuilder();
        var interpolated = false;
        var route = action.Route;
        var i = 0;

        while (i < route.Length)
        {
            if (route[i] != '{')
            {
                result.Append(route[i]);
                i++;

                continue;
            }

            var start = i + 1;
            var end = start;
            while (end < route.Length && (char.IsLetterOrDigit(route[end]) || route[end] == '_'))
                end++;

            var placeholder = route.Substring(start, end - start);
            var parameter = action.Parameters.First(x => x.Kind == ParameterKind.Route && string.Equals(x.WireName, placeholder, StringComparison.OrdinalIgnoreCase));

            result.Append("{(global::System.Uri.EscapeDataString(").Append(Helpers).Append(".Format(").Append(parameter.Name).Append(")))}");
            interpolated = true;

            var close = route.IndexOf('}', end);
            i = close < 0 ? route.Length : close + 1;
        }

        var prefix = interpolated ? "$\"" : "\"";

        return prefix + result + "\"";
    }

    private static string ReturnType(ActionModel action) =>
        action.ResultType is null ? TaskType : $"{TaskType}<{action.ResultType}>";

    private static string Parameters(ActionModel action)
    {
        var parameters = action.Parameters
            .Where(x => x.Kind != ParameterKind.Skipped)
            .Select(x => x.DefaultValue is null ? $"{x.Type} {x.Name}" : $"{x.Type} {x.Name} = {x.DefaultValue}");

        return string.Join(", ", parameters);
    }
}
