<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="TabBlazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Api\EvilCase.Api.Client\EvilCase.Api.Client.csproj" />
    <ProjectReference Include="..\..\Utils\EvilBrains.Logging.Contract\EvilBrains.Logging.Contract.csproj" />
    <ProjectReference Include="..\..\Utils\EvilBrains.Logging.WebAssembly\EvilBrains.Logging.WebAssembly.csproj" />
  </ItemGroup>

</Project>
