CREATE TABLE IF NOT EXISTS "_MigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK__MigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260728185805_Users') THEN
    CREATE TABLE "Users" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(128) NOT NULL,
        "PasswordHash" character varying(128) NOT NULL,
        "Created" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260728185805_Users') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260728185805_Users') THEN
    INSERT INTO "_MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260728185805_Users', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801133505_AuthSessions') THEN
    ALTER TABLE "Users" ALTER COLUMN "PasswordHash" TYPE character varying(256);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801133505_AuthSessions') THEN
    ALTER TABLE "Users" ALTER COLUMN "Email" TYPE character varying(256);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801133505_AuthSessions') THEN
    ALTER TABLE "Users" ADD "FailedLoginAttempts" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801133505_AuthSessions') THEN
    ALTER TABLE "Users" ADD "LockoutEnd" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801133505_AuthSessions') THEN
    ALTER TABLE "Users" ADD "Role" character varying(32) NOT NULL DEFAULT 'User';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801133505_AuthSessions') THEN
    ALTER TABLE "Users" ADD "Updated" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801133505_AuthSessions') THEN
    CREATE TABLE "RefreshTokens" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        "AuthSessionId" uuid NOT NULL,
        "TokenHash" character varying(64) NOT NULL,
        "Created" timestamp with time zone NOT NULL,
        "Expires" timestamp with time zone NOT NULL,
        "SessionExpires" timestamp with time zone NOT NULL,
        "LastUsed" timestamp with time zone,
        "RevokedAt" timestamp with time zone,
        "CreatedByIp" character varying(45),
        "UserAgent" character varying(256),
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801133505_AuthSessions') THEN
    CREATE INDEX "IX_RefreshTokens_AuthSessionId" ON "RefreshTokens" ("AuthSessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801133505_AuthSessions') THEN
    CREATE UNIQUE INDEX "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801133505_AuthSessions') THEN
    CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801133505_AuthSessions') THEN
    INSERT INTO "_MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260801133505_AuthSessions', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801181236_Parties') THEN
    CREATE TABLE "Parties" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "OwnerId" bigint NOT NULL,
        "Kind" character varying(32) NOT NULL,
        "Name" character varying(256) NOT NULL,
        "Address" character varying(1024),
        "DataBoxId" character varying(16),
        "Created" timestamp with time zone NOT NULL,
        "Updated" timestamp with time zone,
        CONSTRAINT "PK_Parties" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Parties_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801181236_Parties') THEN
    CREATE INDEX "IX_Parties_DataBoxId" ON "Parties" ("DataBoxId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801181236_Parties') THEN
    CREATE INDEX "IX_Parties_OwnerId" ON "Parties" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260801181236_Parties') THEN
    INSERT INTO "_MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260801181236_Parties', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802113902_Cases') THEN
    CREATE TABLE "Cases" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "OwnerId" bigint NOT NULL,
        "ParentCaseId" bigint,
        "Title" character varying(256) NOT NULL,
        "Subject" character varying(4000),
        "Status" character varying(32) NOT NULL,
        "Created" timestamp with time zone NOT NULL,
        "Updated" timestamp with time zone,
        CONSTRAINT "PK_Cases" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cases_Cases_ParentCaseId" FOREIGN KEY ("ParentCaseId") REFERENCES "Cases" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Cases_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802113902_Cases') THEN
    CREATE INDEX "IX_Cases_OwnerId" ON "Cases" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802113902_Cases') THEN
    CREATE INDEX "IX_Cases_ParentCaseId" ON "Cases" ("ParentCaseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802113902_Cases') THEN
    CREATE TABLE "CaseTags" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CaseId" bigint NOT NULL,
        "Value" character varying(64) NOT NULL,
        CONSTRAINT "PK_CaseTags" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CaseTags_Cases_CaseId" FOREIGN KEY ("CaseId") REFERENCES "Cases" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802113902_Cases') THEN
    CREATE UNIQUE INDEX "IX_CaseTags_CaseId_Value" ON "CaseTags" ("CaseId", "Value");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802113902_Cases') THEN
    CREATE INDEX "IX_CaseTags_Value" ON "CaseTags" ("Value");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802113902_Cases') THEN
    INSERT INTO "_MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260802113902_Cases', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802172156_CaseReferences') THEN
    ALTER TABLE "Cases" ADD "InternalCaseReference" character varying(64) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802172156_CaseReferences') THEN
    CREATE UNIQUE INDEX "IX_Cases_OwnerId_InternalCaseReference" ON "Cases" ("OwnerId", "InternalCaseReference");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802172156_CaseReferences') THEN
    CREATE TABLE "CaseReferences" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CaseId" bigint NOT NULL,
        "Value" character varying(128) NOT NULL,
        "AssignedByPartyId" bigint NOT NULL,
        "Created" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CaseReferences" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CaseReferences_Cases_CaseId" FOREIGN KEY ("CaseId") REFERENCES "Cases" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CaseReferences_Parties_AssignedByPartyId" FOREIGN KEY ("AssignedByPartyId") REFERENCES "Parties" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802172156_CaseReferences') THEN
    CREATE INDEX "IX_CaseReferences_AssignedByPartyId" ON "CaseReferences" ("AssignedByPartyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802172156_CaseReferences') THEN
    CREATE UNIQUE INDEX "IX_CaseReferences_CaseId_Value" ON "CaseReferences" ("CaseId", "Value");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802172156_CaseReferences') THEN
    CREATE INDEX "IX_CaseReferences_Value" ON "CaseReferences" ("Value");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260802172156_CaseReferences') THEN
    INSERT INTO "_MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260802172156_CaseReferences', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803233913_Acts') THEN
    CREATE TABLE "Acts" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CaseId" bigint NOT NULL,
        "Ordinal" integer NOT NULL,
        "Direction" character varying(32) NOT NULL,
        "Title" character varying(256) NOT NULL,
        "FileNumber" character varying(128),
        "Drafted" date,
        "Sent" date,
        "Delivered" date,
        "Received" date,
        "Summary" text,
        "IssuedByPartyId" bigint,
        "AddressedToPartyId" bigint,
        "Created" timestamp with time zone NOT NULL,
        "Updated" timestamp with time zone,
        CONSTRAINT "PK_Acts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Acts_Cases_CaseId" FOREIGN KEY ("CaseId") REFERENCES "Cases" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Acts_Parties_AddressedToPartyId" FOREIGN KEY ("AddressedToPartyId") REFERENCES "Parties" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Acts_Parties_IssuedByPartyId" FOREIGN KEY ("IssuedByPartyId") REFERENCES "Parties" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803233913_Acts') THEN
    CREATE INDEX "IX_Acts_AddressedToPartyId" ON "Acts" ("AddressedToPartyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803233913_Acts') THEN
    CREATE INDEX "IX_Acts_CaseId" ON "Acts" ("CaseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803233913_Acts') THEN
    CREATE INDEX "IX_Acts_FileNumber" ON "Acts" ("FileNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803233913_Acts') THEN
    CREATE INDEX "IX_Acts_IssuedByPartyId" ON "Acts" ("IssuedByPartyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803233913_Acts') THEN
    INSERT INTO "_MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260803233913_Acts', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234034_FileAssets') THEN
    CREATE TABLE "FileAssets" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "OwnerId" bigint NOT NULL,
        "ContentHash" character varying(64) NOT NULL,
        "SizeBytes" bigint NOT NULL,
        "MediaType" character varying(128),
        "Created" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FileAssets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FileAssets_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234034_FileAssets') THEN
    CREATE TABLE "ActFileLinks" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ActId" bigint NOT NULL,
        "FileAssetId" bigint NOT NULL,
        "Role" character varying(32) NOT NULL,
        "FileName" character varying(256) NOT NULL,
        "OriginatingActId" bigint,
        "Created" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ActFileLinks" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ActFileLinks_Acts_ActId" FOREIGN KEY ("ActId") REFERENCES "Acts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ActFileLinks_Acts_OriginatingActId" FOREIGN KEY ("OriginatingActId") REFERENCES "Acts" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ActFileLinks_FileAssets_FileAssetId" FOREIGN KEY ("FileAssetId") REFERENCES "FileAssets" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234034_FileAssets') THEN
    CREATE INDEX "IX_ActFileLinks_ActId" ON "ActFileLinks" ("ActId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234034_FileAssets') THEN
    CREATE INDEX "IX_ActFileLinks_FileAssetId" ON "ActFileLinks" ("FileAssetId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234034_FileAssets') THEN
    CREATE INDEX "IX_ActFileLinks_OriginatingActId" ON "ActFileLinks" ("OriginatingActId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234034_FileAssets') THEN
    CREATE INDEX "IX_FileAssets_OwnerId" ON "FileAssets" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234034_FileAssets') THEN
    CREATE UNIQUE INDEX "IX_FileAssets_OwnerId_ContentHash" ON "FileAssets" ("OwnerId", "ContentHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234034_FileAssets') THEN
    INSERT INTO "_MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260803234034_FileAssets', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234941_Comments') THEN
    CREATE TABLE "Comments" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CaseId" bigint,
        "ActId" bigint,
        "Body" text NOT NULL,
        "AuthorUserId" bigint NOT NULL,
        "Created" timestamp with time zone NOT NULL,
        "Updated" timestamp with time zone,
        CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Comments_OnACaseOrAnAct" CHECK (("CaseId" IS NULL) <> ("ActId" IS NULL)),
        CONSTRAINT "FK_Comments_Acts_ActId" FOREIGN KEY ("ActId") REFERENCES "Acts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Comments_Cases_CaseId" FOREIGN KEY ("CaseId") REFERENCES "Cases" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Comments_Users_AuthorUserId" FOREIGN KEY ("AuthorUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234941_Comments') THEN
    CREATE INDEX "IX_Comments_ActId" ON "Comments" ("ActId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234941_Comments') THEN
    CREATE INDEX "IX_Comments_AuthorUserId" ON "Comments" ("AuthorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234941_Comments') THEN
    CREATE INDEX "IX_Comments_CaseId" ON "Comments" ("CaseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260803234941_Comments') THEN
    INSERT INTO "_MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260803234941_Comments', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804161531_RenameIdentifiers') THEN
    ALTER TABLE "Cases" RENAME COLUMN "InternalCaseReference" TO "CaseNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804161531_RenameIdentifiers') THEN
    ALTER INDEX "IX_Cases_OwnerId_InternalCaseReference" RENAME TO "IX_Cases_OwnerId_CaseNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804161531_RenameIdentifiers') THEN
    ALTER TABLE "Acts" RENAME COLUMN "FileNumber" TO "ExternalActNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804161531_RenameIdentifiers') THEN
    ALTER INDEX "IX_Acts_FileNumber" RENAME TO "IX_Acts_ExternalActNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804161531_RenameIdentifiers') THEN
    ALTER TABLE "CaseReferences" RENAME TO "ExternalCaseNumbers";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804161531_RenameIdentifiers') THEN
    ALTER INDEX "PK_CaseReferences" RENAME TO "PK_ExternalCaseNumbers";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804161531_RenameIdentifiers') THEN
    ALTER INDEX "IX_CaseReferences_AssignedByPartyId" RENAME TO "IX_ExternalCaseNumbers_AssignedByPartyId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804161531_RenameIdentifiers') THEN
    ALTER INDEX "IX_CaseReferences_CaseId_Value" RENAME TO "IX_ExternalCaseNumbers_CaseId_Value";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804161531_RenameIdentifiers') THEN
    ALTER INDEX "IX_CaseReferences_Value" RENAME TO "IX_ExternalCaseNumbers_Value";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804161531_RenameIdentifiers') THEN
    ALTER TABLE "ExternalCaseNumbers" RENAME CONSTRAINT "FK_CaseReferences_Cases_CaseId" TO "FK_ExternalCaseNumbers_Cases_CaseId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804161531_RenameIdentifiers') THEN
    ALTER TABLE "ExternalCaseNumbers" RENAME CONSTRAINT "FK_CaseReferences_Parties_AssignedByPartyId" TO "FK_ExternalCaseNumbers_Parties_AssignedByPartyId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804161531_RenameIdentifiers') THEN
    INSERT INTO "_MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260804161531_RenameIdentifiers', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804191215_ActDate') THEN
    DROP INDEX "IX_Acts_CaseId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804191215_ActDate') THEN
    ALTER TABLE "Acts" DROP COLUMN "Ordinal";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804191215_ActDate') THEN
    ALTER TABLE "Acts" DROP COLUMN "Drafted";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804191215_ActDate') THEN
    ALTER TABLE "Acts" DROP COLUMN "Sent";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804191215_ActDate') THEN
    ALTER TABLE "Acts" DROP COLUMN "Delivered";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804191215_ActDate') THEN
    ALTER TABLE "Acts" DROP COLUMN "Received";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804191215_ActDate') THEN
    ALTER TABLE "Acts" ADD "Date" date NOT NULL DEFAULT DATE '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804191215_ActDate') THEN
    ALTER TABLE "Acts" ALTER COLUMN "Date" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804191215_ActDate') THEN
    CREATE INDEX "IX_Acts_CaseId_Date" ON "Acts" ("CaseId", "Date");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "_MigrationsHistory" WHERE "MigrationId" = '20260804191215_ActDate') THEN
    INSERT INTO "_MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260804191215_ActDate', '10.0.10');
    END IF;
END $EF$;
COMMIT;

