<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Api\EvilCase.Api.Contract\EvilCase.Api.Contract.csproj" />
    <ProjectReference Include="..\..\Data\EvilCase.Data\EvilCase.Data.csproj" />
    <ProjectReference Include="..\..\Domain\EvilCase.Domain\EvilCase.Domain.csproj" />
  </ItemGroup>

</Project>
