<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Api\EvilCase.Api.Contract\EvilCase.Api.Contract.csproj" />
    <ProjectReference Include="..\..\Data\EvilCase.Data\EvilCase.Data.csproj" />
    <ProjectReference Include="..\EvilCase.Domain\EvilCase.Domain.csproj" />
  </ItemGroup>

</Project>
