<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="OpenAI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Data\EvilBrains.AI.Data\EvilBrains.AI.Data.csproj" />
  </ItemGroup>

</Project>
